# baseURL = 'http://localhost:1313/'
baseURL = 'https://ricclegg.github.io/2001project/'
languageCode = 'en-us'
title = '2OO1: Project'
theme = '2001project'
publishDir = "docs"


[params]
  author = "Richard Clegg"
  description = "A log of my \"2OO1: Project\" recreation journey."
